### ISSUE TITLE
Database needed

### ISSUE THREAD

**Issue by ankampraveenkitsw** [Nabil5352/School-Management-System#2]
Hi. Can you please send me the Database for this project.

Thanks in advance..

**Comment by Nabil5352** [comment]
Hey @ankampraveenkitsw , this project was done a long time ago. This was a university project and I didn't take any db backup for that. Sorry for your trouble.

**Comment by latheeshmahendran** [comment]
Can you support us by giving a db for tht project of yours, since I find it more interesting, It could help me practice. Thank you

**Comment by Bilal6029** [comment]
Could you please share the  DB so we can demosntrate the demo
